/**
 * Database Types
 *
 * This file is auto-generated by running `npx symulate import-schema`
 * Run this command after your backend team uploads a database schema to Symulate.
 *
 * DO NOT edit this file manually - it will be overwritten.
 */

// Placeholder - will be populated by import-schema command
export const DatabaseTypes = {} as const;

// Example of what this file looks like after running import-schema:
/*
export const DatabaseTypes = {
  users: {
    id: "uuid",
    name: "varchar(255)",
    email: "varchar(255)",
    created_at: "timestamptz",
    role: "varchar(50)"
  },
  posts: {
    id: "uuid",
    title: "varchar(500)",
    content: "text",
    author_id: "uuid",  // FK to users.id
    published_at: "timestamptz"
  }
} as const;

export interface User {
  id: string;
  name: string;
  email: string;
  created_at: string;
  role: string;
}

export interface Post {
  id: string;
  title: string;
  content: string;
  author_id: string;
  published_at: string;
}
*/
